name: CI

on: [push]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: php-actions/composer@v6

      - uses: php-actions/phpunit@v4
        with:
          php_version: '8.1'
          bootstrap: vendor/autoload.php
          configuration: phpunit.xml
